### ISSUE TITLE
Notify users about 3rd party cookies

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA-LTI#1]
Since LTI providers are nearly always "3rd parties" (that is, separate from the site that is running the LMS or other portal to the content), we need to gracefully handle the situation where users have turned off 3rd party cookies. This probably would be done with some sort of popup. It might need to be browser-specific, or better, point to a page with detailed instructions by browser.

**Comment by hosamshahin** [comment]
To be implemented in the Rails app.

**Comment by awhicks** [comment]
The same site cookie attribute we added should take care of this
