### ISSUE TITLE
`last_comment` is deprecated

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA-LTI#18]
Whenever we do something with the database, we get warning messages such as:

[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

For example, when updating the development environment, there is a step as:

  rake db:reset_populate

This will generate several instances of the warning message.

**Comment by hosamshahin** [comment]
Warning message disappears after upgrading 'rspec-rails', '>=3.4.2'

https://github.com/ruby/rake/issues/133
