### ISSUE TITLE
Issues for some PEs and AVs

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#2]
- MergesortPro shows up with the canvas not having enough space to hold everything. Not sure how you set this.
- MergesortPRO, for example, has a "help" button that points to another page. I am guessing that the issue is merely that you didn't include that page in your files.
- BSTinsertPRO (both versions) have options in the settings menu to change the language (written or code). When the user tries to set them, the page will reload. In this case, Canvas displays a "Not Found" page.

**Comment by cashaffer** [comment]
This is OpenDSA content stuff, does not belong here. I'll take care of these, its on my TODO list now.
