### ISSUE TITLE
New Course Offering form

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA-LTI#25]
There is no field for "institution" on the New Course Offering form. There is a list of courses. I am guessing that it is "all" courses. Selecting the institution should then populate this course list menu.

If we want to encourage "Self Enrollment Allowed", then the default should be to have that box checked.

There needs to be an explanation of what the "Label" field is about, if it needs to be there at all.

There ought to be a "help message" available (tied to a little ? icon or something) to explain the LMS COURSE CODE and LMS COURSE NUMBER fields.

**Comment by hosamshahin** [comment]
New course offering form should take care of all the issues here.
