### ISSUE TITLE
Password reset support does not work

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA-LTI#29]
If a user tries to sign in and gives a bad email (or ID), they are taken to a page that gives them another chance to log in, along with a bunch of buttons.

One of these is "Forgot your password?". This takes you to a form with a button "Send me reset password instructions". That does not work, it gives a syntax error page.

Another button says "Sign in with Cas". That also does not work (it just hangs). And it should read "CAS" rather than "Cas".

**Comment by cashaffer** [comment]
I did not try Oauth or Facebook signin.

**Comment by cashaffer** [comment]
BTW, I see no mechanism for admins to reset a user's password.

**Comment by hosamshahin** [comment]
Users can click "Forgot user password?" link in the login page to reset their password.
