### ISSUE TITLE
Can't run Shotgun on Windows

### ISSUE THREAD

**Issue by acbart** [OpenDSA/OpenDSA-LTI#3]
Shotgun does not run on windows because it relies on certain Unix features ([SIGQUIT and fork](https://github.com/rtomayko/shotgun/issues/40)). Therefore, an alternative is to use [sinatra-reloader](http://www.sinatrarb.com/contrib/reloader.html), part of sinatra-contrib, run through rackup or a similar system. 

I've gotten the system running using this instead. In the spirit of supporting Windows, I committed this version (9245ed0) and you can tell me if it's acceptable. It should have the exact same configuration and everything, it just drops the reliance on shotgun.

**Comment by hosamshahin** [comment]
Closing this issue since we already moved to Rails.
