### ISSUE TITLE
Link to Canvas course

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA-LTI#33]
When logged in at the OpenDSA Instructor/Admin site, and browsing through the course list (http://opendsa.org/courses), there is no way to get to the actual Canvas site associated with a course. There is not even an indication of which Canvas site any given course is associated with.

**Comment by hosamshahin** [comment]
Canvas course links will be shown to **admins** in the courses view (see below screenshot). However, whether they can access the canvas course or not depends on their enrollment into that canvas course.

![image](https://cloud.githubusercontent.com/assets/6162247/21695929/c98736a4-d359-11e6-909b-1a03d96dd737.png)
 
**Instructors** on the other hand will get their canvas course link in the course offering view (see below screenshot)

![image](https://cloud.githubusercontent.com/assets/6162247/21696051/429f7b50-d35a-11e6-83ac-d9877c863d0c.png)

**Comment by cashaffer** [comment]
Only Admins? Why shouldn't instructors be able to get to courses?

**Comment by hosamshahin** [comment]
Instructors will be able to go to **their** courses, but only admins will have access to **all** courses.

**Comment by cashaffer** [comment]
Should be working now.
