### ISSUE TITLE
Book configuration view changes

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#34]
1- Date picker is no longer working in section due dates
2- Section due dates are set to today's date when they are null, while they should be kept as null.
3- Remove the following fields from the options
- instance book id
- course id
- LMS url
- build_dir
- code_dir
- build_JSAV
- build_cmap
- suppress_todo
- dispModComp
- glob_exer_options
- assumes
4- Remove the following fields from each section:
- all fields start with 'lms_'
5- Include only 'points' and 'threshold' in the exercises object
6- True/False fields should be a radio button instead of drop-down list
7- Try to arrange section fields and exercises fields horizontally to save space and to make it looks more organized.
8- Remove the expand/collapse icon if the module doesn't have any sections
9- Add undo button to revert back all user changes
10- If 'last_compiled' field exists in the book configuration object and it wasn't empty, that means the book was already compiled. In this case user should not be allowed to change chapters/modules order.
11- Chapter date picker dialog box is very wide. The width should be adjusted to just fit the due dates fields.

**Comment by taylorr7** [comment]
I just pushed a change that should fix 2, 3, 4, 5, 6, 8, 9 and 11.

**Comment by hosamshahin** [comment]
A list of exercises comes under a section, however when an exercise object is empty (doesn't have "points", "threshold" etc.) it is actually a diagram not an exercise. Since there is no special configurations for diagrams we should remove them from the configuration view.

So in the below example, remove the diagram ADTCON: {}

![image](https://cloud.githubusercontent.com/assets/6162247/21617609/d304b586-d1b4-11e6-82ac-b4a63acf52e9.png)

**Comment by hosamshahin** [comment]
- Exercises ends with "CON" usually have 0 points, so we shouldn't show it in the configuration view for now. So any section can have up to only one gradable exercise.

**Comment by taylorr7** [comment]
Fixed issue 10 and the new issues (hiding diagrams, hiding 'CON' exercises and changing 'soft_deadline' to 'due_date'). Still have to fix issue 1 and 7.

**Comment by hosamshahin** [comment]
Adding to point 10, If 'last_compiled' field exists in the book configuration object and it wasn't empty, users should not be allowed to delete chapters.

**Comment by taylorr7** [comment]
Users can no longer delete chapters if 'last_compiled' exists.

I still need to fix issue 7 but I believe the rest have been fixed.
