### ISSUE TITLE
Book configuration update 

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#35]
I tried to change one of the exercises points and save the book configuration, but I got an error in the browser console saying:

![image](https://cloud.githubusercontent.com/assets/6162247/21503487/ce63ff62-cc25-11e6-93d8-8dc4ba137d68.png)

I've looked into the generated Json object, the problem is in unnecessary field 'value' after 'showsection'.
**"showsection": "true" value="true",**

,  "chapters": { 
    "Sorting": { 
      "Sorting/InSort": {},
      "Sorting/SortNotation": { 
        "Sorting Terminology and Notation": { 
          "soft_deadline": "12/27/2016 12:00 AM",
          "hard_deadline": "12/27/2016 12:00 AM",
          "showsection": "true" value="true",
          "lms_item_id": null,
          "lms_assignment_id": null,
          "SortIntroSumm": { 
            "long_name": "Sorting Intro Summary",
            "required": "true" value="true",
            "points": 10,
            "threshold": 3,
            "options": null
          }
        }

**Comment by taylorr7** [comment]
This should be fixed now! Let me know if you're still having this problem and I'll take another look.
