### ISSUE TITLE
Book configuration view validation rules

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#36]
Here are some rules to validate before sending instructor changes to the server. If any if these rules is violated a clear error message should be shown to the instructor.

- Title and Description fields are not null
- DateTime format is "%Y-%m-%d %H:%m:%S" ex. "2016-12-14 23:12:48"
- Points field is decimal
- Threshold field for exercises ends with "PRO" is decimal from 0 to 1.0 
- Threshold field for other exercises is integer from 1 to 10. It is recommended to have a little up and down arrows to increase and decrease the field value using the mouse instead of typing.

**Comment by taylorr7** [comment]
This should now be done. I still have to edit the input box for thresholds with the arrows like suggested but the validation itself works.

**Comment by hosamshahin** [comment]
It turned out that some KA exercises end with "PRO" so the validation rule should be 

- Threshold field should be decimal from 0 to 1.0 OR integer from 1 to 10

**Comment by hosamshahin** [comment]
The validation error message should be modified to show a clearer source of error. For example
SOURCE: Sorting/Quicksort/QuicksortPivotPRO should be 
SOURCE: Sorting/Quicksort/Introduction (chapter/module/section name)

**Comment by taylorr7** [comment]
Just to check, do you want the validation rule for all threshold fields to be 0 to 1.0 OR 1 to 10, or do you want that for just the ones that end with "PRO"?

**Comment by hosamshahin** [comment]
For all threshold fields.

**Comment by taylorr7** [comment]
I fixed the validation rule. I'm still working on getting the error message to display the correct location to the error.

**Comment by taylorr7** [comment]
The error message should display correctly now!

**Comment by hosamshahin** [comment]
Validation is not working, I tried to assign 100 and -1 to points, in both cases I didn't get the error validation message. 
![image](https://cloud.githubusercontent.com/assets/6162247/21912572/c3ac9184-d8f4-11e6-9dfb-e5f578a6bc0f.png)

But when I tried non-numeric value I got:
![image](https://cloud.githubusercontent.com/assets/6162247/21912591/e394c0f2-d8f4-11e6-9520-9cde2241d6f9.png)

I suggest reformating the error SOURCE to be

SOURCE: **Chapter**: Sorting **Module**: Insertion Sort **Section**: Insertion Sort **Exercise**: Insertion Sort Proficiency Exercise

**Comment by taylorr7** [comment]
I changed the 'source' to be closer to what you described. Let me know how it looks!

I also just changed it so you can no longer enter negative values for the points. Can you remind me what the upper-bound for the points field should be?

**Comment by hosamshahin** [comment]
Threshold field should be decimal from 0 to 1.0 OR integer from 1 to 10

**Comment by taylorr7** [comment]
This should already be the case for Thresholds (although, let me know if that is not working for you).
Should I do the same for Points?
