### ISSUE TITLE
Book configuration - Date picker for section due date is not working 

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#37]
![image](https://cloud.githubusercontent.com/assets/6162247/21619401/831a3182-d1bd-11e6-918b-324c79ebb976.png)

**Comment by taylorr7** [comment]
I just pushed a temporary fix for this. The datepicker should now display, however, the 'minute' picker is not visible.

**Comment by hosamshahin** [comment]
When I click the button to the right of the date field nothing happen. Date picker dialog won't appear until I select the date field **then** click the button.

**Comment by taylorr7** [comment]
This should be fixed now.
