### ISSUE TITLE
Book configuration -- incorrect json sent to the server 

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#39]
The generated json file is missing module long_name and sections fields. I've included sample module comparison below. The left part is the correct format, the right part is the generated json

![image](https://cloud.githubusercontent.com/assets/6162247/21621120/a122aeae-d1c5-11e6-996b-2fa41aae84f7.png)

**Comment by taylorr7** [comment]
I think I have fixed this. long_name and sections should both appear in the generated json now.

Let me know if there are any other changes that need to be made to the json for it to work properly!
