### ISSUE TITLE
Book configuration - Show section

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#44]
Remove show section attribute for now.

**Comment by hosamshahin** [comment]
BTW, when I choose True or False I got the following error in the console

Uncaught Error: Syntax error, unrecognized expression: [object HTMLFormElement]input[type='radio']:checked
    at Function.Sizzle.error (jquery.js?body=1:1474)
    at Sizzle.tokenize (jquery.js?body=1:2088)
    at Sizzle.select (jquery.js?body=1:2489)
    at Function.Sizzle [as find] (jquery.js?body=1:880)
    at jQuery.fn.init.find (jquery.js?body=1:2705)
    at jQuery.fn.init (jquery.js?body=1:2822)
    at jQuery (jquery.js?body=1:74)
    at HTMLFormElement.<anonymous> (inst_books.js?body=1:50)
    at HTMLDocument.dispatch (jquery.js?body=1:4642)
    at HTMLDocument.elemData.handle (jquery.js?body=1:4310)

**Comment by taylorr7** [comment]
I have hidden the show section attribute and will look into the cause of that error.

**Comment by taylorr7** [comment]
I have fixed this error!

**Comment by cashaffer** [comment]
The ability to remove a section has to be restored. We have  modules that are deliberately designed to only display one from a choice of sections. In fact, we might consider making a special designation for such modules, so that at configuration time the instructor must pick from a choice.

**Comment by taylorr7** [comment]
What would be the best way to do this? Should I just restore the "showsection" radio button? Or should I try to implement a system that allows you to delete certain sections?

**Comment by hosamshahin** [comment]
Taylor -- from your side the only thing to do is to restore the show section radio button.

**Comment by taylorr7** [comment]
I just restored the button!

**Comment by cashaffer** [comment]
This is not fixing my problem. We have it in both the "Plain" and the Canvas books. See the last module in the Algorithm Analysis chapter for CS2 and CS3. CS2 should show ONLY the first exercise,and CS3 should show ONLY the second exercise. The config files specify what should happen. But the compilation process seems to ignore that.

**Comment by hosamshahin** [comment]
The compilation process will generate the book html pages under /Books/book_name/html and another set of section level html pages under /Books/book_name/lti_html. The latter folder is used to serve the LTI version while the former is used for plain books. 

For LTI it should be straightforward when a section is hidden just skip the section file in the course generation step. While in the plain version the compilation process should be changed to entirely remove the hidden sections from a module file.

I can take care of LTI version. However, to update the compilation process will need some time to figure it out.

**Comment by taylorr7** [comment]
Just a thought, I could try to add something the configuration view that checks the status of the 'showsection' button and, if it is false, removes that section entirely from the JSON object that I'm sending to the server. Would that fix the problem? Or would it cause issues having the sections not in the configuration?

**Comment by cashaffer** [comment]
This used to work correctly. So the fact that "plain" books are not removing sections means that something happened to break this process.

The best approach is that the compilation process will not pass through sections that are not supposed to be there. We don't want to create the HTML files and then "suppress" them somehow.

**Comment by awhicks** [comment]
Did this get resolved? Unless I'm misunderstanding, this is in the book configuration view and does work now, but I'm not 100% sure

**Comment by awhicks** [comment]
I was misunderstanding, the book configuration view is broken and most of these need reassessed
