### ISSUE TITLE
Book Configuration - Header fields

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#45]
![image](https://cloud.githubusercontent.com/assets/6162247/21754559/e40a1888-d5d0-11e6-9a97-c0545a18d83b.png)

- Use proper fields titles punctuation and fields width.
- Remove extra horizontal white line after description field.

**Comment by hosamshahin** [comment]
Also proper fields width for exercises names

![image](https://cloud.githubusercontent.com/assets/6162247/21754598/6cc8dd6c-d5d1-11e6-924f-e71227b5814e.png)

**Comment by taylorr7** [comment]
This should be fixed now!

**Comment by hosamshahin** [comment]
title -> Title 
description -> Description

**Comment by taylorr7** [comment]
Done! All of the fields should have proper capitalization now.

**Comment by awhicks** [comment]
This might be fixed, but it is currently not displayed
