### ISSUE TITLE
Book configuration -- Chapter Due Date is not working

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#48]
When I selected the date field the date picker dialog didn't show up, rather it was placed under the date field in the same dialog.

**Comment by taylorr7** [comment]
Could you attach a screenshot of this perhaps? As far as I can tell, it seems to be working properly on my branch.

**Comment by taylorr7** [comment]
I also made a few changes to the styling on the datepicker so that might have fixed the issue as well. Let me know if it is still a problem.
