### ISSUE TITLE
Date picker layout is not correct

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA-LTI#50]
Hours and minutes should be placed under the days, not to the right.

**Comment by taylorr7** [comment]
For whatever reason, when I try to move hours and minutes below under the days, the entire datepicker disappears.

![datepicker](https://cloud.githubusercontent.com/assets/22223890/22118101/75f32e08-de44-11e6-9280-5faca9972c39.png)

I'm looking into what could be the cause of this, just letting you know that this one might be a little tricky.

**Comment by hosamshahin** [comment]
You can ask @ayaankazerouni, he is already using the date picker in CodeWorkout.

**Comment by taylorr7** [comment]
I fixed the hours/minutes issue but now the datepicker is displaying in the wrong color. I'm sure this will be an easy fix and I should have that pushed soon, I just wanted to push the now functional datepicker since that was done.

**Comment by taylorr7** [comment]
I fixed the color now. This should be working. Let me know how it looks!

**Comment by awhicks** [comment]
I think these actually aren't fixed, unless I'm missing something, these should be the Book configuration view, which doesn't do any of these things right now, but seems like it should
