### ISSUE TITLE
Possible Missing Setting in Ubuntu18Install.md

### ISSUE THREAD

**Issue by AlecGoncharow** [OpenDSA/OpenDSA-LTI#61]
[File in question](https://github.com/OpenDSA/OpenDSA-LTI/blob/master/Ubuntu18Install.md)

It may be necessary to include some mention of `passenger_ruby /home/deploy/.rbenv/shims/ruby;`, possibly in the "Final Steps" section when the user is editing the `/etc/nginx/sites-enabled/default`

**Comment by cashaffer** [comment]
Thanks for pointing this out! Hamza will look into it.
