### ISSUE TITLE
Can't create course offering through GUI or through Admin

### ISSUE THREAD

**Issue by acbart** [OpenDSA/OpenDSA-LTI#63]
I've been trying to create a new course offering on the https://opendsa-server.cs.vt.edu/ site, but it won't let me through either the [form](https://opendsa-server.cs.vt.edu/course_offerings/new) or the [admin panel](https://opendsa-server.cs.vt.edu/admin/course_offerings). 

In the form, it demands that I have a valid access token for my Moodle course - but I don't have one. I was going to load in content using the LTI Content-Item method, since we have webservices turned off on Moodle (and since our server requires VPN access, it's not like anything could be done if I did have one). I can't find any clever way to convince the form that to ignore that field, so it's not letting me submit.

In the admin panel, when I click the "New Course Offering" button, I get the following error message:

    NoMethodError undefined method `user=' for #<CourseOffering:0x007f3b615005e8> Did you mean? users= users

**Comment by jwonderly** [comment]
This has been addressed here: 1b4c60cc2a05f3d722746a8e0a0af142659675c4

The issue was mainly because we recently updated Rails, and apparently the behavior of the JSON serialization function we were using changed. This led to some issues with wrong/invalid data being passed to the front-end.
